### ISSUE TITLE
aligned deallocation is only available on macOS 10.13 or newer

### ISSUE THREAD

**Issue by ryandesign** [nghttp2/nghttp2#2227]
Building nghttp2 1.62.1 on macOS 10.12 and older fails:

```
In file included from http2.cc:25:
In file included from ./http2.h:40:
In file included from ./util.h:59:
./allocator.h:104:7: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.13 or newer
  104 |       operator delete[](reinterpret_cast<uint8_t *>(mb), std::align_val_t(16));
      |       ^
./allocator.h:104:7: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
./allocator.h:113:18: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer
  113 |     auto block = new (std::align_val_t(16)) uint8_t[sizeof(MemBlock) + size];
      |                  ^
./allocator.h:113:18: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
./allocator.h:113:18: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.13 or newer
  113 |     auto block = new (std::align_val_t(16)) uint8_t[sizeof(MemBlock) + size];
      |                  ^
./allocator.h:113:18: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
```

Presumably caused by 9260e53410ea9786f0f936b03157049176b7d3ab.

**Comment by ryandesign** [comment]
Specifically this is when using the configure argument `--enable-app`. It doesn't happen when using `--enable-lib-only`.
