### ISSUE TITLE
'mruby' was not declared in this scope ?

### ISSUE THREAD

**Issue by centminmod** [nghttp2/nghttp2#1219]
make stage seems to be failing in my latest docker rebuild with nghttp2 1.33 while fine with 1.31 with ubuntu artful 17

```
make -j$(nproc) 
make  all-recursive
make[1]: Entering directory '/usr/local/src/nghttp2'
Making all in lib
make[2]: Entering directory '/usr/local/src/nghttp2/lib'
Making all in includes
make[3]: Entering directory '/usr/local/src/nghttp2/lib/includes'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/usr/local/src/nghttp2/lib/includes'
make[3]: Entering directory '/usr/local/src/nghttp2/lib'
  CC       nghttp2_pq.lo
  CC       nghttp2_map.lo
  CC       nghttp2_queue.lo
  CC       nghttp2_frame.lo
  CC       nghttp2_buf.lo
  CC       nghttp2_session.lo
  CC       nghttp2_stream.lo
  CC       nghttp2_outbound_item.lo
  CC       nghttp2_submit.lo
  CC       nghttp2_helper.lo
  CC       nghttp2_npn.lo
  CC       nghttp2_hd.lo
  CC       nghttp2_hd_huffman.lo
  CC       nghttp2_hd_huffman_data.lo
  CC       nghttp2_version.lo
  CC       nghttp2_priority_spec.lo
  CC       nghttp2_option.lo
  CC       nghttp2_callbacks.lo
  CC       nghttp2_mem.lo
  CC       nghttp2_http.lo
  CC       nghttp2_rcbuf.lo
  CC       nghttp2_debug.lo
  CCLD     libnghttp2.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/usr/local/src/nghttp2/lib'
make[2]: Leaving directory '/usr/local/src/nghttp2/lib'
Making all in third-party
make[2]: Entering directory '/usr/local/src/nghttp2/third-party'
  CC       http-parser/http_parser.lo
  CCLD     libhttp-parser.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/usr/local/src/nghttp2/third-party'
Making all in src
make[2]: Entering directory '/usr/local/src/nghttp2/src'
Making all in includes
make[3]: Entering directory '/usr/local/src/nghttp2/src/includes'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/usr/local/src/nghttp2/src/includes'
make[3]: Entering directory '/usr/local/src/nghttp2/src'
  CXX      libnghttpx_a-util.o
  CXX      libnghttpx_a-http2.o
  CC       libnghttpx_a-timegm.o
  CXX      libnghttpx_a-app_helper.o
  CXX      libnghttpx_a-tls.o
  CXX      libnghttpx_a-shrpx_config.o
  CXX      libnghttpx_a-shrpx_accept_handler.o
  CXX      libnghttpx_a-shrpx_connection_handler.o
  CXX      libnghttpx_a-shrpx_client_handler.o
  CXX      libnghttpx_a-shrpx_http2_upstream.o
  CXX      libnghttpx_a-shrpx_https_upstream.o
  CXX      libnghttpx_a-shrpx_downstream.o
  CXX      libnghttpx_a-shrpx_downstream_connection.o
  CXX      libnghttpx_a-shrpx_http_downstream_connection.o
  CXX      libnghttpx_a-shrpx_http2_downstream_connection.o
  CXX      libnghttpx_a-shrpx_http2_session.o
  CXX      libnghttpx_a-shrpx_downstream_queue.o
  CXX      libnghttpx_a-shrpx_log.o
  CXX      libnghttpx_a-shrpx_http.o
  CXX      libnghttpx_a-shrpx_io_control.o
  CXX      libnghttpx_a-shrpx_tls.o
  CXX      libnghttpx_a-shrpx_worker.o
  CXX      libnghttpx_a-shrpx_log_config.o
  CXX      libnghttpx_a-shrpx_connect_blocker.o
  CXX      libnghttpx_a-shrpx_live_check.o
  CXX      libnghttpx_a-shrpx_downstream_connection_pool.o
  CXX      libnghttpx_a-shrpx_rate_limit.o
  CXX      libnghttpx_a-shrpx_connection.o
shrpx_worker.cc: In member function 'void shrpx::Worker::replace_downstream_config(std::shared_ptr<shrpx::DownstreamConfig>)':
shrpx_worker.cc:187:39: error: 'mruby' was not declared in this scope
   std::map<StringRef, std::shared_ptr<mruby::MRubyContext>> shared_mruby_ctxs;
                                       ^~~~~
shrpx_worker.cc:187:58: error: template argument 1 is invalid
   std::map<StringRef, std::shared_ptr<mruby::MRubyContext>> shared_mruby_ctxs;
                                                          ^~
shrpx_worker.cc:187:61: error: template argument 2 is invalid
   std::map<StringRef, std::shared_ptr<mruby::MRubyContext>> shared_mruby_ctxs;
                                                             ^~~~~~~~~~~~~~~~~
shrpx_worker.cc:187:61: error: template argument 4 is invalid
  CXX      libnghttpx_a-shrpx_memcached_dispatcher.o
  CXX      libnghttpx_a-shrpx_memcached_connection.o
  CXX      libnghttpx_a-shrpx_worker_process.o
Makefile:1825: recipe for target 'libnghttpx_a-shrpx_worker.o' failed
make[3]: *** [libnghttpx_a-shrpx_worker.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/usr/local/src/nghttp2/src'
Makefile:2565: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/src/nghttp2/src'
Makefile:567: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/nghttp2'
Makefile:476: recipe for target 'all' failed
make: *** [all] Error 2
```

```
configure: summary of build options:

    Package version: 1.33.0-DEV
    Library version: 30:3:16
    Install prefix:  /usr/local
    System types:
      Build:         x86_64-pc-linux-gnu
      Host:          x86_64-pc-linux-gnu
      Target:        x86_64-pc-linux-gnu
    Compiler:
      C compiler:     gcc
      CFLAGS:         -g -O2
      LDFLAGS:        
      C++ compiler:   g++
      CXXFLAGS:       -g -O2
      CXXCPP:         g++ -E
      C preprocessor: gcc -E
      CPPFLAGS:       
      WARNCFLAGS:     
      WARNCXXFLAGS:   
      CXX1XCXXFLAGS:  
      EXTRACFLAG:     -fvisibility=hidden
      LIBS:           
    Library:
      Shared:         yes
      Static:         yes
    Python:
      Python:         /usr/bin/python
      PYTHON_VERSION: 2.7
      pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
      Python-dev:     yes
      PYTHON_CPPFLAGS:-I/usr/include/python2.7
      PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
      Cython:         cython
    Test:
      CUnit:          yes (CFLAGS='' LIBS='-lcunit')
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes (CFLAGS='-I/usr/local/http2-15/include' LIBS='-L/usr/local/http2-15/lib -lssl -lcrypto')
      Libxml2:        yes (CFLAGS='' LIBS='-lxml2')
      Libev:          yes (CFLAGS='' LIBS='-lev')
      Libc-ares       yes (CFLAGS='' LIBS='-lcares')
      Libevent(SSL):  yes (CFLAGS='-I/usr/local/http2-15/include' LIBS='-L/usr/local/http2-15/lib -levent_openssl -levent')
      Jansson:        yes (CFLAGS='' LIBS='-ljansson')
      Jemalloc:       yes (LIBS='-ljemalloc')
      Zlib:           yes (CFLAGS='' LIBS='-lz')
      Systemd:        no (CFLAGS='' LIBS='')
      Boost CPPFLAGS: -pthread -I/usr/include
      Boost LDFLAGS:  -L/usr/lib/x86_64-linux-gnu
      Boost::ASIO:    -lboost_system
      Boost::System:  -lboost_system
      Boost::Thread:  -lboost_thread
    Third-party:
      http-parser:    yes
      MRuby:          no (CFLAGS='' LIBS='')
      Neverbleed:     no
    Features:
      Applications:   yes
      HPACK tools:    yes
      Libnghttp2_asio:yes
      Examples:       yes
      Python bindings:yes
      Threading:      yes
```

**Comment by tatsuhiro-t** [comment]
Thank you for telling me.  It was fixed via commit fb9a204d

**Comment by centminmod** [comment]
Thanks @tatsuhiro-t very much appreciated :)
