### ISSUE TITLE
error: This file requires compiler and library support for the ISO C++ 2011 standard.

### ISSUE THREAD

**Issue by noloader** [nghttp2/nghttp2#1454]
Hi Everyone,

I am testing nghttp2-1.40.0.tar.gz on Solaris 11.3, amd64. Solaris provides older tools and libraries. Oracle generally requires a support contract to purchase updated tools and bug fixes.

Configure went going well, but compile is having some issues:

```
g++ -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR=/usr/local/share/nghttp2 -I../lib/inc
ludes -I../lib/includes -I../lib -I../src/includes -I../third-party -I../third-p
arty/llhttp/include -I/usr/local/include/libxml2 -I/usr/local/include -I/usr/loc
al/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -DHAVE
_CONFIG_H -I/usr/local/include -DNDEBUG   -g2 -O2 -m64 -march=native -fPIC -pthr
ead -MT deflatehd.o -MD -MP -MF $depbase.Tpo -c -o deflatehd.o deflatehd.cc &&
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/gcc/4.8/include/c++/4.8.2/array:35:0,
                 from template.h:34,
                 from inflatehd.cc:46:
/usr/gcc/4.8/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This fil
e requires compiler and library support for the ISO C++ 2011 standard. This supp
ort is currently experimental, and must be enabled with the -std=c++11 or -std=g
nu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
```

It might be a good idea to have `configure` check for C++11, and add `-std=c++11` as needed.

**Comment by zhendehaofan** [comment]
how to fix it?

**Comment by zhendehaofan** [comment]
update your gcc.
compile pass after i update gcc to 8.4.0

**Comment by noloader** [comment]
Thanks @zhendehaofan .

Sun doe snot allow the upgrade (unless you purchase a maintenance contract). We are kind of stuck with what we have.

**Comment by paulmenzel** [comment]
The requirements are right there in the https://github.com/nghttp2/nghttp2/blob/master/README.rst.

> Compiling libnghttp2 C source code requires a C99 compiler. gcc 4.8 is known to be adequate. In
> order to compile the C++ source code, gcc >= 6.0 or clang >= 6.0 is required. C++ source code
> requires C++14 language features.

@noloader, why should somebody invest resources and time into supporting your outdated setup? It’d be great if you closed the issue (and updated the issue description beforehand). Please buy the maintenance contract, build GCC yourself, or contract/pay somebody else to fix this issue.
