### ISSUE TITLE
suggest a variable name change in 1.65.0 "extern nghttp2_stream root"

### ISSUE THREAD

**Issue by stxyang** [nghttp2/nghttp2#2376]
Hi Tatsuhiro,

When bumping nghttp2 to v1.65.0, my project build reported an error.

At global scope:
include/nghttp2_session.h:48:23: error: 'nghttp2_stream root' redeclared as different kind of entity
 48 | extern nghttp2_stream root;

I already had a global function "void root()", so a conflict was there.
I changed the function name to a more specific one and bypass the issue. 

Is it ok to change the "root" to "nghttp2_stream_root" in nghttp2_session.h, so that other one would avoid such conflict.

あなたのライブラリに感謝します、本当に素晴らしいです！

-Stanley
