### ISSUE TITLE
Fails to build with new libevent 2.1.13

### ISSUE THREAD

**Issue by david-geiger** [nghttp2/nghttp2#2832]
Hi,

On Mageia Cauldron latest release fails to build with new libevent 2.1.13:

> /usr/include/event2/event.h:844:5: error: conflicting types for 'event_base_loopexit'; have 'int(struct event_base *, const struct timeval *)'
  844 | int event_base_loopexit(struct event_base *, const struct timeval *);
      |     ^~~~~~~~~~~~~~~~~~~
In file included from libevent-client.c:61:
/usr/include/libev/event.h:164:5: note: previous declaration of 'event_base_loopexit' with type 'int(struct event_base *, struct timeval *)'
  164 | int event_base_loopexit (struct event_base *base, struct timeval *tv);
      |     ^~~~~~~~~~~~~~~~~~~
/usr/include/event2/event.h:1209:5: error: conflicting types for 'event_base_once'; have 'int(struct event_base *, int,  short int,  void (*)(int,  short int,  void *), void *, const struct timeval *)'
 1209 | int event_base_once(struct event_base *, evutil_socket_t, short, event_callback_fn, void *, const struct timeval *);
      |     ^~~~~~~~~~~~~~~
/usr/include/libev/event.h:166:5: note: previous declaration of 'event_base_once' with type 'int(struct event_base *, int,  short int,  void (*)(int,  short int,  void *), void *, struct timeval *)'
  166 | int event_base_once (struct event_base *base, int fd, short events, void (*cb)(int, short, void *), void *arg, struct timeval *tv);
      |     ^~~~~~~~~~~~~~~
/usr/include/event2/event.h:1233:5: error: conflicting types for 'event_add'; have 'int(struct event *, const struct timeval *)'
 1233 | int event_add(struct event *ev, const struct timeval *timeout);
      |     ^~~~~~~~~
/usr/include/libev/event.h:151:5: note: previous declaration of 'event_add' with type 'int(struct event *, struct timeval *)'
  151 | int event_add (struct event *ev, struct timeval *tv);
      |     ^~~~~~~~~
/usr/include/event2/event.h:1307:5: error: conflicting types for 'event_pending'; have 'int(const struct event *, short int,  struct timeval *)'
 1307 | int event_pending(const struct event *ev, short events, struct timeval *tv);
      |     ^~~~~~~~~~~~~
/usr/include/libev/event.h:155:5: note: previous declaration of 'event_pending' with type 'int(struct event *, short int,  struct timeval *)'
  155 | int event_pending (struct event *ev, short, struct timeval *tv);
      |     ^~~~~~~~~~~~~
/usr/include/event2/event.h:1334:5: error: expected identifier or '(' before 'const'
 1334 | int event_initialized(const struct event *ev);
      |     ^~~~~~~~~~~~~~~~~
/usr/include/libev/event.h:110:41: error: expected ')' before '->' token
  110 | #define event_initialized(ev)      ((ev)->ev_flags & EVLIST_INIT)

Attached full build log:

[build.x86_64.0.20260830033816.log](https://github.com/user-attachments/files/31607847/build.x86_64.0.20260830033816.log)

**Comment by nsr990** [comment]
> Hi,
> 
> On Mageia Cauldron latest release fails to build with new libevent 2.1.13:
> 
> > /usr/include/event2/event.h:844:5: error: conflicting types for 'event_base_loopexit'; have 'int(struct event_base *, const struct timeval *)'
>   844 | int event_base_loopexit(struct event_base *, const struct timeval *);
>       |     ^~~~~~~~~~~~~~~~~~~
> In file included from libevent-client.c:61:
> /usr/include/libev/event.h:164:5: note: previous declaration of 'event_base_loopexit' with type 'int(struct event_base *, struct timeval *)'
>   164 | int event_base_loopexit (struct event_base *base, struct timeval *tv);
>       |     ^~~~~~~~~~~~~~~~~~~
> /usr/include/event2/event.h:1209:5: error: conflicting types for 'event_base_once'; have 'int(struct event_base *, int,  short int,  void (*)(int,  short int,  void *), void *, const struct timeval *)'
>  1209 | int event_base_once(struct event_base *, evutil_socket_t, short, event_callback_fn, void *, const struct timeval *);
>       |     ^~~~~~~~~~~~~~~
> /usr/include/libev/event.h:166:5: note: previous declaration of 'event_base_once' with type 'int(struct event_base *, int,  short int,  void (*)(int,  short int,  void *), void *, struct timeval *)'
>   166 | int event_base_once (struct event_base *base, int fd, short events, void (*cb)(int, short, void *), void *arg, struct timeval *tv);
>       |     ^~~~~~~~~~~~~~~
> /usr/include/event2/event.h:1233:5: error: conflicting types for 'event_add'; have 'int(struct event *, const struct timeval *)'
>  1233 | int event_add(struct event *ev, const struct timeval *timeout);
>       |     ^~~~~~~~~
> /usr/include/libev/event.h:151:5: note: previous declaration of 'event_add' with type 'int(struct event *, struct timeval *)'
>   151 | int event_add (struct event *ev, struct timeval *tv);
>       |     ^~~~~~~~~
> /usr/include/event2/event.h:1307:5: error: conflicting types for 'event_pending'; have 'int(const struct event *, short int,  struct timeval *)'
>  1307 | int event_pending(const struct event *ev, short events, struct timeval *tv);
>       |     ^~~~~~~~~~~~~
> /usr/include/libev/event.h:155:5: note: previous declaration of 'event_pending' with type 'int(struct event *, short int,  struct timeval *)'
>   155 | int event_pending (struct event *ev, short, struct timeval *tv);
>       |     ^~~~~~~~~~~~~
> /usr/include/event2/event.h:1334:5: error: expected identifier or '(' before 'const'
>  1334 | int event_initialized(const struct event *ev);
>       |     ^~~~~~~~~~~~~~~~~
> /usr/include/libev/event.h:110:41: error: expected ')' before '->' token
>   110 | #define event_initialized(ev)      ((ev)->ev_flags & EVLIST_INIT)
> 
> Attached full build log:
> 
> [build.x86_64.0.20260830033816.log](https://github.com/user-attachments/files/31607847/build.x86_64.0.20260830033816.log)
