### ISSUE TITLE
shrpx_listen_handler.cc fails to compile on armel architecture with g++ 4.9.1

### ISSUE THREAD

**Issue by dajobe** [nghttp2/nghttp2#86]
The debian autobuilders reported a failure building nghttp2 on the `armel` architecture which seems to be some kind of C++ issue that's beyond my experience.   The fragment of the error reported in Debian bug [763906](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763906) in the [Build Log](https://buildd.debian.org/status/fetch.php?pkg=nghttp2&arch=armel&ver=0.6.2-2&stamp=1412353887) is as follows

```
In file included from shrpx_listen_handler.cc:25:0:
shrpx_listen_handler.h:49:21: error: field 'fut' has incomplete type 'std::future<void>'
   std::future<void> fut;
                     ^
shrpx_listen_handler.cc: In member function 'void shrpx::ListenHandler::create_worker_thread(size_t)':
shrpx_listen_handler.cc:140:38: error: invalid use of incomplete type 'class std::future<void>'
                            info.get());
                                      ^
In file included from shrpx_listen_handler.h:36:0,
                 from shrpx_listen_handler.cc:25:
/usr/include/c++/4.9/future:114:11: error: declaration of 'class std::future<void>'
     class future;
           ^
make[4]: *** [shrpx_listen_handler.o] Error 1
Makefile:1250: recipe for target 'shrpx_listen_handler.o' failed
```

The tool package versions are: binutils_2.24.51.20140918-1 dpkg-dev_1.17.13 g++-4.9_4.9.1-15 gcc-4.9_4.9.1-15 libc6-dev_2.19-11 libstdc++-4.9-dev_4.9.1-15 libstdc++6_4.9.1-15 linux-libc-dev_3.16.3-2
