### ISSUE TITLE
v1.36.0 fails to build on OS X 10.11.6

### ISSUE THREAD

**Issue by leonklingele** [nghttp2/nghttp2#1309]
v1.36.0 fails to build on OS X 10.11.6 (installed with Homebrew):

```
[..]
clang++ -std=c++14 -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/usr/local/Cellar/nghttp2/1.36.0/share/nghttp2"' -I../lib/includes -I../lib/incl
udes -I../lib -I../src/includes -I../third-party -I/usr/include/libxml2 -I/usr/local/Cellar/openssl/1.0.2q/include -I/usr/local/Cellar/c-are
s/1.15.0/include -I/usr/local/Cellar/jansson/2.12/include -DHAVE_CONFIG_H      -g -O2 -MT libnghttpx_a-shrpx_downstream.o -MD -MP -MF .deps/
libnghttpx_a-shrpx_downstream.Tpo -c -o libnghttpx_a-shrpx_downstream.o `test -f 'shrpx_downstream.cc' || echo './'`shrpx_downstream.cc
mv -f .deps/libnghttpx_a-shrpx_accept_handler.Tpo .deps/libnghttpx_a-shrpx_accept_handler.Po
clang++ -std=c++14 -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/usr/local/Cellar/nghttp2/1.36.0/share/nghttp2"' -I../lib/includes -I../lib/incl
udes -I../lib -I../src/includes -I../third-party -I/usr/include/libxml2 -I/usr/local/Cellar/openssl/1.0.2q/include -I/usr/local/Cellar/c-are
s/1.15.0/include -I/usr/local/Cellar/jansson/2.12/include -DHAVE_CONFIG_H      -g -O2 -MT libnghttpx_a-shrpx_downstream_connection.o -MD -MP
 -MF .deps/libnghttpx_a-shrpx_downstream_connection.Tpo -c -o libnghttpx_a-shrpx_downstream_connection.o `test -f 'shrpx_downstream_connecti
on.cc' || echo './'`shrpx_downstream_connection.cc
shrpx_client_handler.cc:1166:10: error: no viable conversion from returned value of type 'unique_ptr<shrpx::HttpDownstreamConnection, default_delete<shrpx::HttpDownstreamConnection>>' to function return type 'unique_ptr<shrpx::DownstreamConnection, default_delete<shrpx::DownstreamConnection>>'
  return dconn;
         ^~~~~
```

```sh
$ clang++ --version | head -n2
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
```

Possibly related to #1305.

**Comment by vdupom** [comment]
Same error present in 1.37.0 for OS X 10.11.6

```bash
$ clang++ --version | head -n2
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
```

**Comment by noplanman** [comment]
Check #1319, those code changes fix the build failing.

What I did:
- Download the package: `brew fetch nghttp2`
- Change into the Homebrew cache folder: `cd $HOME/Library/Caches/Homebrew`
- Extract the archive: `tar xJf nghttp2--1.38.0.tar.xz`
- Apply the code changes from #1319: `sed -ibkp 's/return dconn;/return std::move(dconn);/g' nghttp2-1.38.0/src/shrpx_client_handler.cc`
- Compress the files to an archive and replace the original one: `tar cJf nghttp2--1.38.0.tar.xz nghttp2-1.38.0`
- Get the checksum of the new archive: `sha256sum nghttp2--1.38.0.tar.xz | awk '{print $1}'`
- Enter the new checksum in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nghttp2.rb`
- Attempt upgrade again

**Comment by vdupom** [comment]
Worked for me, thanks!

**Comment by noplanman** [comment]
To simplify the process, as this happens with each new release of nghttp2, I've written a small script that automates all of this, you can find it here:
https://gist.github.com/noplanman/eb360d6e82ec0d58a9da884bd4b279d1

Just download and execute :wink:

**Comment by hotalo** [comment]
@noplanman thank you

**Comment by rosswilson252** [comment]
@noplanman Thanks, man!

Just need the smallest of tweaks (`upgrade-nghttp2` instead of`update-nghttp2`) but work like a treat! Thank you.

**Comment by noplanman** [comment]
@rosswilson252 Eagle eye, thanks for spotting that 🙏
Have "updated" my comment 😋

**Comment by noplanman** [comment]
Hi all, I've updated my gist as it stopped working with the latest version of brew.

So it should work again now 🍷

**Comment by muj-programmer** [comment]
I think the `nghttp2`@team should look into this matter and provide a proper fix to this.

It was really time taking to search for this issue on my machine and then I opened the github repo issues section and hopefully found the fix, thanks to @noplanman.
